.TH FNMTOOL 1 "FidoNetMailTOOL (0.02)"
.SH NAME
fnmtool \- Read and scan your FidoNet netmail folder and takes some action
according the config file. 
May forward netmail to your internet mail account and gated back.
.SH SYNTAX
.B fnmtool
    -s  run silent

    -d  with debug output

    -h -? --help  this screen

.SH DESCRIPTION
fnmtool will scan your netmail folder and copy, move according to yout setup.
.SH BUGS
a lot of them
.SH STABILITY
what's that??? ;)
.SH AUTHOR
Michael Mleczko (mm3d@gmx.net)
Ruedi Kneubuehler (ruedi@baboon.ch)
 
